=== NhutKTPM/XML_BTNhom_Nhom1_QLTourDuLich/qltourjson/tour.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Tour",
  "type": "object",
  "properties": {
    "maTour": {
      "type": "string",
      "pattern": "[A-Za-z0-9\\-]+",
      "description": "Mã tour, ví dụ T001",
      "maxLength": 10
    },
    "tenHdv": {
      "type": "string",
      "description": "Tên hướng dẫn viên",
      "maxLength": 50
    },
    "tenTour": {
      "type": "string",
      "maxLength": 50
    },
    "moTa": {
      "type": "string",
      "maxLength": 255

    },
    "ngayBatDau": {
      "type": "string",
      "format": "date",
      "description": "YYYY-MM-DD"
    },
    "ngayKetThuc": {
      "type": "string",
      "format": "date",
      "description": "YYYY-MM-DD"
    },
    "lichTrinh": {
      "type": "string",
      "maxLength": 255
    },
    "diaDiemRefs": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "maTour",
    "tenHdv",
    "tenTour",
    "ngayBatDau",
    "ngayKetThuc",
    "lichTrinh",
    "diaDiemRefs"
  ],
  "additionalProperties": false
}

=== NhutKTPM/XML_BTNhom_Nhom1_QLTourDuLich/qltourjson/tour.json
{
  "maTour": "T001",
  "tenHdv": "Phạm Thị Cúc",
  "tenTour": "Tour Hà Nội - Hạ Long",
  "moTa": "Tham quan Hà Nội và Vịnh Hạ Long 4 ngày 3 đêm",
  "ngayBatDau": "2025-10-01",
  "ngayKetThuc": "2025-10-04",
  "lichTrinh": "Ngày 1: Tham quan Hồ Gươm, Lăng Bác.\nNgày 2: Tham quan Hoàng Thành Thăng Long.\nNgày 3: Tham quan Vịnh Hạ Long.\nNgày 4: Tự do tham quan, mua sắm",
  "diaDiemRefs": ["Hồ Gươm", "Lăng Bác"," Hoàng Thành Thăng Long", "Vịnh Hạ Long"]
}
